=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/digitalni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat"
           xmlns:ds="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat"
           xmlns:tp="http://www.rokzasok.rs/tipovi" xmlns:r="http://www.w3.org/ns/rdfa#" xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/">

    <xs:import namespace="http://www.rokzasok.rs/tipovi" schemaLocation="tipovi.xsd"/>

    <xs:element name="digitalni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gradjanin">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="ds:TOsoba">
                                <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate"
                                              name="vocab" type="xs:string"/>
                                <xs:attribute name="about" type="xs:string"/>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vakcinacija">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="doza">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="ds:TDoza">
                                            <xs:attribute
                                                    fixed="http://www.rokzasok.rs/rdf/database/predicate"
                                                    name="vocab" type="xs:string"/>
                                            <xs:attribute name="about" type="xs:string"/>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="testovi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="3" minOccurs="3" name="test" type="ds:TTest"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="info_o_sertifikatu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="qr_link">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute default="pred:qrLink" name="property"
                                                          type="xs:string"/>
                                            <xs:attribute default="xs:string" name="datatype"
                                                          type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute default="pred:datumIzdavanja"
                                                          name="property" type="xs:string"/>
                                            <xs:attribute default="xs:string" name="datatype"
                                                          type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="broj_sertifikata" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dokument_id" type="xs:positiveInteger"/>
            </xs:sequence>
            <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate" name="vocab"
                          type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
            <xs:attribute default="pred:kreiranOdStrane" name="rel" type="xs:string"/>
            <xs:attribute default="xs:string" name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="TTest">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="opis" type="xs:string"/>
            <xs:element default="N/A" name="vrsta_uzorka" type="xs:string"/>
            <xs:element default="N/A" name="proizvodjac" type="xs:string"/>
            <xs:element name="datum_i_vreme_uzorkovanja" type="xs:string"/>
            <xs:element name="datum_i_vreme_rezultata" type="xs:string"/>
            <xs:element default="N/A" name="rezultat" type="xs:string"/>
            <xs:element default="N/A" name="laboratorija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="jmbg" type="tp:T_JMBG"/>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="pol">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="tp:T_pol"> </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum_rodjenja">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date"> </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="adresa" type="ds:TAdresa"/>
            <xs:element name="broj_pasosa">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="tp:T_broj_pasosa"> </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDoza">
        <xs:sequence>
            <xs:element name="tip">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="ds:T_tip_vakcine"> </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="proizvodjac">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="ds:T_proizvodjac_vakcine"/>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="datum">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:date"/>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="broj_serije">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string"/>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="broj_doze">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:positiveInteger"/>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="ustanova" type="ds:TUstanova"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Mesto" type="xs:string"/>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TUstanova">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="T_tip_vakcine">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pfizer-BioNtech"/>
            <xs:enumeration value="Sputnik V (Gamaleya istraživački centar)"/>
            <xs:enumeration value="Sinopharm"/>
            <xs:enumeration value="AstraZeneca"/>
            <xs:enumeration value="Moderna"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_proizvodjac_vakcine">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BioNTech Manufacturing GMBH"/>
            <xs:enumeration value="Sinopharm"/>
            <xs:enumeration value="Gamaleya Institute"/>
            <xs:enumeration value="Oxford"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/digitalni_sertifikat_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds:digitalni_sertifikat xmlns:ds="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat"
                         xmlns:tp="http://www.rokzasok.rs/tipovi"
                         xmlns="http://www.w3.org/ns/rdfa#"
                         xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat schema/digitalni_sertifikat.xsd"
                         vocab="http://www.rokzasok.rs/rdf/database/predicate"
                         about="http://www.rokzasok.rs/rdf/database/digitalni-sertifikat/1" rel="pred:kreiranOdStrane"
                         xmlns:xs="http://www.w3.org/2001/XMLSchema#"
                         href="http://www.rokzasok.rs/rdf/database/osoba/1234567890231">
    <ds:gradjanin>
        <ds:jmbg>1234567890231</ds:jmbg>
        <ds:ime>Isi</ds:ime>
        <ds:prezime>Prezimic</ds:prezime>
        <ds:pol>Z</ds:pol>
        <ds:datum_rodjenja>1999-12-10</ds:datum_rodjenja>
        <ds:adresa>
            <ds:Mesto>Novi Sad</ds:Mesto>
            <ds:Ulica>Ulica</ds:Ulica>
            <ds:Broj>3</ds:Broj>
        </ds:adresa>
        <ds:broj_pasosa>123456789</ds:broj_pasosa>
        <ds:id>69420</ds:id>
    </ds:gradjanin>
    <ds:vakcinacija>
        <ds:doza vocab="http://www.rokzasok.rs/rdf/database/predicate" about="http://www.rokzasok.rs/rdf/database/doza/1">
            <ds:tip>Pfizer-BioNtech</ds:tip>
            <ds:proizvodjac>BioNTech Manufacturing GMBH</ds:proizvodjac>
            <ds:datum>2021-03-05</ds:datum>
            <ds:broj_serije>2345</ds:broj_serije>
            <ds:broj_doze>1</ds:broj_doze>
            <ds:ustanova>
                <ds:naziv>VMA</ds:naziv>
                <ds:mesto>BG</ds:mesto>
            </ds:ustanova>
        </ds:doza>
    </ds:vakcinacija>
    <ds:testovi>
        <ds:test>
            <ds:naziv>Test1</ds:naziv>
            <ds:opis>opis0</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>N/A</ds:naziv>
            <ds:opis>N/A</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>naziv2</ds:naziv>
            <ds:opis>opis2</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>datum_i_vreme_uzorkovanja2</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>datum_i_vreme_rezultata2</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
    </ds:testovi>
    <ds:info_o_sertifikatu>
        <ds:qr_link property="pred:qrLink" datatype="xs:string">qr_link0</ds:qr_link>
        <ds:datum datatype="xs:string" property="pred:datumIzdavanja">2006-05-04</ds:datum>
        <ds:broj_sertifikata>1</ds:broj_sertifikata>
    </ds:info_o_sertifikatu>
    <ds:dokument_id>1</ds:dokument_id>
</ds:digitalni_sertifikat>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/najnoviji-digitalni-sertifikat-primer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds:digitalni_sertifikat xmlns:ds="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat"
 xmlns:tp="http://www.rokzasok.rs/tipovi"
 xmlns:r="http://www.w3.org/ns/rdfa#"
 xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat file:/Users/jovandjordjic/Documents/fakultet/xml/projekat-git/portal.za.imunizaciju/src/main/resources/data/schema/digitalni_sertifikat.xsd">
    <ds:gradjanin>
        <ds:jmbg>1234567891011</ds:jmbg>
        <ds:ime>Marko</ds:ime>
        <ds:prezime>MarkoviÄ‡</ds:prezime>
        <ds:pol>M</ds:pol>
        <ds:datum_rodjenja>1952-10-07</ds:datum_rodjenja>
        <ds:broj_pasosa>1234567890</ds:broj_pasosa>
        <ds:id>1</ds:id>
    </ds:gradjanin>
    <ds:vakcinacija>
    </ds:vakcinacija>
    <ds:testovi>
        <ds:test>
            <ds:naziv>SARS-COV-2 RT</ds:naziv>
            <ds:opis>Real-time PCR</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>SARS-COV-2 Ag-RDT</ds:naziv>
            <ds:opis>(Antigen Rapid Detection test)</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>SARS-COV-2 RBD S-Protein</ds:naziv>
            <ds:opis>Immunoglobulin G (IgG) test</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>

    </ds:testovi>
    <ds:info_o_sertifikatu>
        <ds:qr_link>sertifikat.com</ds:qr_link>
        <ds:datum>2022-02-27T18:13:51.0</ds:datum>
    </ds:info_o_sertifikatu>
    <ds:dokument_id>1</ds:dokument_id>
</ds:digitalni_sertifikat>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/bkp-primeri/digitalni_sertifikat_primer-bkp.xml
<?xml version="1.0" encoding="UTF-8"?>
<ds:digitalni_sertifikat xmlns:ds="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rokzasok.rs/sluzbenik/digitalni-sertifikat schema/digitalni_sertifikat.xsd">
    <ds:gradjanin>
        <!-- Ovo može da bude tabela "Osoba/Građanin" -->
        <ds:jmbg>1234567890231</ds:jmbg>
        <ds:ime>Isi</ds:ime>
        <ds:prezime>Isi</ds:prezime>
        <ds:pol>M</ds:pol>
        <ds:datum_rodjenja>1999-12-10</ds:datum_rodjenja>
        <ds:adresa>
            <ds:Mesto>NS</ds:Mesto>
            <ds:Ulica>Ul</ds:Ulica>
            <ds:Broj>1234</ds:Broj>
        </ds:adresa>
        <ds:broj_pasosa>123456789</ds:broj_pasosa>
    </ds:gradjanin>
    <ds:vakcinacija>
        <ds:doza>
            <ds:tip>Pfeizer-BioNTech</ds:tip> <!-- Ovo može da bude veza ka tabeli "Vakcina/Tip vakcine" -->
            <ds:proizvodjac>BioNTech Manufacturing GMBH</ds:proizvodjac> <!-- Ovo može da bude veza ka tabeli "Proizvođač vakcine" ILI JOŠ BOLJE - Tip Vakcine proizvodi proizvođač, proizvođač proizvodi tip vakcine -->
            <ds:datum>2021-03-05</ds:datum>
            <ds:broj_serije>2345</ds:broj_serije>
            <ds:broj_doze>1</ds:broj_doze>
            <ds:ustanova>
                <ds:naziv>VMA</ds:naziv>
                <ds:mesto>BG</ds:mesto>
            </ds:ustanova>
        </ds:doza>
    </ds:vakcinacija>
    <ds:testovi>
        <ds:test>
            <ds:naziv>ewasdtfg</ds:naziv>
            <ds:opis>asfdghj</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>N/A</ds:naziv>
            <ds:opis>N/A</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
        <ds:test>
            <ds:naziv>N/A</ds:naziv>
            <ds:opis>N/A</ds:opis>
            <ds:vrsta_uzorka>N/A</ds:vrsta_uzorka>
            <ds:proizvodjac>N/A</ds:proizvodjac>
            <ds:datum_i_vreme_uzorkovanja>N/A</ds:datum_i_vreme_uzorkovanja>
            <ds:datum_i_vreme_rezultata>N/A</ds:datum_i_vreme_rezultata>
            <ds:rezultat>N/A</ds:rezultat>
            <ds:laboratorija>N/A</ds:laboratorija>
        </ds:test>
    </ds:testovi>
    <ds:info_o_sertifikatu>
        <ds:qr_link>www.google.com</ds:qr_link>
        <ds:datum>2021-12-30</ds:datum>
        <ds:broj_sertifikata>123456</ds:broj_sertifikata>
    </ds:info_o_sertifikatu>
    <ds:dokument_id>123456</ds:dokument_id>
</ds:digitalni_sertifikat>
