=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/iskazivanje_interesovanja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../grddl.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja"
    xmlns="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja"
    xmlns:ns1="http://www.rokzasok.rs/tipovi" xmlns:r="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/">

    <xs:import namespace="http://www.rokzasok.rs/tipovi" schemaLocation="tipovi.xsd"/>
    <xs:element name="obrazac_interesovanja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podaci_o_osobi"
                    r:vocab="http://www.rokzasok.rs/rdf/database/predicate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="drzavljanstvo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="T_drzavljanstvo">
                                            <xs:attribute default="xs:string" name="datatype"
                                                type="xs:string"/>
                                            <xs:attribute default="pred:drzavljanstvo"
                                                name="property" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="ns1:JMBG"/>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="email">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ns1:T_email">
                                            <xs:attribute default="pred:email" name="property"
                                                type="xs:string"/>
                                            <xs:attribute default="xs:string" name="datatype"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="broj_mobilnog_telefona" type="ns1:T_mobilni"/>
                            <xs:element name="broj_fiksnog_telefona">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="ns1:T_fiksni">
                                            <xs:attribute default="pred:brojFiksnogTelefona"
                                                name="property" type="xs:string"/>
                                            <xs:attribute default="xs:string" name="datatype"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="vocab" type="xs:string"
                            fixed="http://www.rokzasok.rs/rdf/database/predicate"/>
                        <xs:attribute name="about" type="xs:string" use="optional"/>
                        <xs:attribute name="idOsobe" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:long"/>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="opsti_podaci"
                    r:vocab="http://www.rokzasok.rs/rdf/database/predicate">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lokacija_opstina">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute default="pred:lokacijaOpstina"
                                                name="property" type="xs:string"/>
                                            <xs:attribute default="xs:string" name="datatype"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:sequence maxOccurs="1">
                                <xs:element name="tip_vakcine">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="T_tip_vakcine">
                                                <xs:attribute default="pred:tipVakcine"
                                                  name="property" type="xs:string"/>
                                                <xs:attribute default="xs:string" name="datatype"
                                                  type="xs:string"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                            <xs:element name="davalac_krvi">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:boolean">
                                            <xs:attribute default="pred:davalacKrvi" name="property"
                                                type="xs:string"/>
                                            <xs:attribute default="xs:boolean" name="datatype"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_podnosenja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute default="pred:datumPodnosenja"
                                                name="property" type="xs:string"/>
                                            <xs:attribute default="xs:date" name="datatype"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate"
                            name="vocab" type="xs:string"/>
                        <xs:attribute name="about" type="xs:string"/>
                        <xs:attribute default="pred:kreiranOdStrane" name="rel" type="xs:string"/>
                        <xs:attribute name="href" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dokument_id" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="T_tip_vakcine">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pfizer-BioNtech"/>
            <xs:enumeration value="Sputnik V (Gamaleya istraživački centar)"/>
            <xs:enumeration value="Sinopharm"/>
            <xs:enumeration value="AstraZeneca"/>
            <xs:enumeration value="Moderna"/>
            <xs:enumeration value="Bilo koja"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="T_drzavljanstvo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Državljanin Republike Srbije"/>
            <xs:enumeration value="Strani državljanin sa boravkom u RS"/>
            <xs:enumeration value="Strani državljanin bez boravka u RS"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/iskazivanje_interesovanja_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<is:obrazac_interesovanja xmlns:ns1="http://www.rokzasok.rs/tipovi"
                          xmlns:r="http://www.w3.org/ns/rdfa#"
                          xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
                          xmlns:is="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja schema/iskazivanje_interesovanja.xsd">
    <is:podaci_o_osobi>
        <is:drzavljanstvo>Državljanin Republike Srbije</is:drzavljanstvo>
        <ns1:JMBG>1234567891011</ns1:JMBG>
        <is:ime>Marko</is:ime>
        <is:prezime>Marković</is:prezime>
        <is:email>m.markovic@mailinator.com</is:email>
        <is:broj_mobilnog_telefona>066123456</is:broj_mobilnog_telefona>
        <is:broj_fiksnog_telefona>021123456</is:broj_fiksnog_telefona>
    </is:podaci_o_osobi>
    <is:opsti_podaci>
        <is:lokacija_opstina>Novi Sad</is:lokacija_opstina>
        <is:tip_vakcine>Pfizer-BioNtech</is:tip_vakcine>
        <is:davalac_krvi>false</is:davalac_krvi>
        <is:datum_podnosenja>2022-02-27</is:datum_podnosenja>
        <is:idPodnosioca>1</is:idPodnosioca>
    </is:opsti_podaci>
    <is:dokument_id>1</is:dokument_id>
</is:obrazac_interesovanja>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/iskazivanje_interesovanja_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<is:obrazac_interesovanja xmlns:ns1="http://www.rokzasok.rs/tipovi"
                          xmlns="http://www.w3.org/ns/rdfa#"
                          xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
                          xmlns:is="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xmlns:xs="http://www.w3.org/2001/XMLSchema#"
                          xsi:schemaLocation="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja schema/iskazivanje_interesovanja.xsd">
    <is:podaci_o_osobi vocab="http://www.rokzasok.rs/rdf/database/predicate" about="http://www.rokzasok.rs/rdf/database/osoba/1001999980035">
        <is:drzavljanstvo>Državljanin Republike Srbije</is:drzavljanstvo>
        <ns1:JMBG>1001999980035</ns1:JMBG>
        <is:ime>Jovan</is:ime>
        <is:prezime>Đorđić</is:prezime>
        <is:email>jovan.d@mail.info</is:email>
        <is:broj_mobilnog_telefona>066488755</is:broj_mobilnog_telefona>
        <is:broj_fiksnog_telefona>021666877</is:broj_fiksnog_telefona>
    </is:podaci_o_osobi>
    <is:opsti_podaci
            vocab="http://www.rokzasok.rs/rdf/database/predicate"
            about="http://www.rokzasok.rs/rdf/database/iskazivanje-interesovanja/1"
            rel="pred:kreiranOdStrane" href="http://www.rokzasok.rs/rdf/database/osoba/1001999980035">
        <is:lokacija_opstina>Novi Sad</is:lokacija_opstina>
        <is:tip_vakcine>Pfizer-BioNtech</is:tip_vakcine>
        <is:davalac_krvi>false</is:davalac_krvi>
        <is:datum_podnosenja>2022-01-03</is:datum_podnosenja>
    </is:opsti_podaci>
    <is:dokument_id>1</is:dokument_id>
</is:obrazac_interesovanja>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/bkp-primeri/iskazivanje_interesovanja_primer-bkp.xml
<?xml version="1.0" encoding="UTF-8"?>
<obrazac_interesovanja xmlns="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rokzasok.rs/gradjanin/iskazivanje-interesovanja iskazivanje_interesovanja.xsd">
    <podaci_o_osobi>
        <drzavljanstvo>Državljanin Republike Srbije</drzavljanstvo>
        <JMBG xmlns="http://www.rokzasok.rs/tipovi">1305999700064</JMBG>
        <ime>Jovan</ime>
        <prezime>Đorđić</prezime>
        <email>jovandjordjic@gmail.com</email>
        <broj_mobilnog_telefona>063551744</broj_mobilnog_telefona>
        <broj_fiksnog_telefona>021777893</broj_fiksnog_telefona>
    </podaci_o_osobi>
    <opsti_podaci>
        <lokacija_opstina>Novi Sad</lokacija_opstina>
        <tip_vakcine>Pfizer-BioNtech</tip_vakcine>
        <davalac_krvi>0</davalac_krvi>
        <datum_podnosenja>2021-11-15</datum_podnosenja>
    </opsti_podaci>
    <dokument_id>12345</dokument_id>
</obrazac_interesovanja>
