=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.rokzasok.rs/sluzbenik/izvestaj-o-imunizaciji"
    xmlns:ioi="http://www.rokzasok.rs/sluzbenik/izvestaj-o-imunizaciji">

    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="br_interesovanja" type="xs:positiveInteger"/>
                <xs:element name="br_primljenih_zahteva_za_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="br_izdatih_zahteva_za_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="br_doza_zbirno" type="xs:positiveInteger"/>
                <xs:element name="doze_vakcina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" name="doza">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="redni_broj_doze" type="xs:positiveInteger"/>
                                        <xs:element name="broj_datih" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="raspodela_po_proizvodjacima">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="proizvodjac" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Pfizer, BioNTech"/>
                                                  <xs:enumeration value="Sinopharm"/>
                                                  <xs:enumeration value="Sputnik V"/>
                                                  <xs:enumeration value="AstraZeneca, Oxford"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="broj_primljenih_doza"
                                            type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_izdavanja" type="xs:date"/>
                <xs:element name="period_izvestaja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="od" type="xs:date"/>
                            <xs:element name="do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dokument_id" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/izvestaj_o_imunizaciji_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj_o_imunizaciji xmlns="http://www.rokzasok.rs/sluzbenik/izvestaj-o-imunizaciji"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rokzasok.rs/sluzbenik/izvestaj-o-imunizaciji schema/izvestaj_o_imunizaciji.xsd">
    <br_interesovanja>452</br_interesovanja>
    <br_primljenih_zahteva_za_sertifikat>567</br_primljenih_zahteva_za_sertifikat>
    <br_izdatih_zahteva_za_sertifikat>452</br_izdatih_zahteva_za_sertifikat>
    <br_doza_zbirno>3267</br_doza_zbirno>
    <doze_vakcina>
        <doza>
            <redni_broj_doze>1</redni_broj_doze>
            <broj_datih>1789</broj_datih>
        </doza>
        <doza>
            <redni_broj_doze>2</redni_broj_doze>
            <broj_datih>1289</broj_datih>
        </doza>
        <doza>
            <redni_broj_doze>3</redni_broj_doze>
            <broj_datih>189</broj_datih>
        </doza>
    </doze_vakcina>
    <raspodela_po_proizvodjacima>
        <proizvodjac>
            <naziv>Pfizer, BioNTech</naziv>
            <broj_primljenih_doza>1400</broj_primljenih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>Sinopharm</naziv>
            <broj_primljenih_doza>1500</broj_primljenih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>Sputnik V</naziv>
            <broj_primljenih_doza>100</broj_primljenih_doza>
        </proizvodjac>
        <proizvodjac>
            <naziv>AstraZeneca, Oxford</naziv>
            <broj_primljenih_doza>89</broj_primljenih_doza>
        </proizvodjac>
    </raspodela_po_proizvodjacima>
    <datum_izdavanja>2021-09-11</datum_izdavanja>
    <period_izvestaja>
        <od>2021-08-01</od>
        <do>2021-09-01</do>
    </period_izvestaja>
    <dokument_id>123456</dokument_id>
</izvestaj_o_imunizaciji>
