=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/potvrda_vakcinacije.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije"
    xmlns="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije"
    xmlns:tp="http://www.rokzasok.rs/tipovi" xmlns:r="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/">
    <!--
        Definition: Vaccination certificate document type
        Author: Matija Matovic -->

    <xs:import namespace="http://www.rokzasok.rs/tipovi" schemaLocation="tipovi.xsd"/>

    <xs:element name="potvrda-vakcinacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="osoba">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jmbg" type="tp:T_JMBG"/>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="pol">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="tp:T_pol"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="datum_rodjenja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate"
                            name="vocab" type="xs:string"/>
                        <xs:attribute name="about" type="xs:string"/>
                        <xs:attribute name="idOsobe" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:long"/>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="doze">
                    <xs:complexType>
                        <xs:sequence minOccurs="2" maxOccurs="unbounded">
                            <xs:element name="doza">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="T_doza">
                                            <xs:attribute
                                                fixed="http://www.rokzasok.rs/rdf/database/predicate"
                                                name="vocab" type="xs:string"/>
                                            <xs:attribute default="xs:string" name="about"
                                                type="xs:string"/>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="razlog_izdavanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute default="pred:razlogIzdavanja" name="property"
                                    type="xs:string"/>
                                <xs:attribute default="xs:string" name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_izdavanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute default="pred:datumIzdavanja" name="property"
                                    type="xs:string"/>
                                <xs:attribute default="xs:date" name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dokument_id" type="xs:positiveInteger"/>
            </xs:sequence>
            <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate" name="vocab"
                type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
            <xs:attribute default="pred:kreiranOdStrane" name="rel" type="xs:string"/>
            <xs:attribute default="xs:string" name="href" type="xs:string"/>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="T_osoba">
        <xs:sequence>
            <xs:element name="jmbg" type="tp:T_JMBG"/>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="pol" type="tp:T_pol"/>
            <xs:element name="datum_rodjenja" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_doza">
        <xs:sequence>
            <xs:element name="tip">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Pfizer-BioNtech"/>
                        <xs:enumeration value="Sputnik V (Gamaleya istraživački centar)"/>
                        <xs:enumeration value="Sinopharm"/>
                        <xs:enumeration value="AstraZeneca"/>
                        <xs:enumeration value="Moderna"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="proizvodjac">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="BioNTech Manufacturing GMBH"/>
                        <xs:enumeration value="Sinopharm"/>
                        <xs:enumeration value="Gamaleya Institute"/>
                        <xs:enumeration value="Oxford"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="broj_serije" type="xs:string"/>
            <xs:element name="broj_doze" type="xs:positiveInteger"/>
            <xs:element name="ustanova" type="T_ustanova"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="T_ustanova">
        <xs:sequence>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/potvrda_vakcinacije_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<po:potvrda-vakcinacije xmlns:tp="http://www.rokzasok.rs/tipovi"
                        xmlns="http://www.w3.org/ns/rdfa#"
                        xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
                        xmlns:po="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije schema/potvrda_vakcinacije.xsd"
                        about="http://www.rokzasok.rs/rdf/database/potvrda-vakcinacije/1" rel="pred:kreiranOdStrane"
                        xmlns:xs="http://www.w3.org/2001/XMLSchema#"
                        href="http://www.rokzasok.rs/rdf/database/osoba/1234567890123"
                        vocab="http://www.rokzasok.rs/rdf/database/predicate">
    <po:osoba vocab="http://www.rokzasok.rs/rdf/database/predicate"
              about="http://www.rokzasok.rs/rdf/database/osoba/1234567890123" idOsobe="1234">
        <po:jmbg>1234567890123</po:jmbg>
        <po:ime>Zdravko</po:ime>
        <po:prezime>Krivokapic</po:prezime>
        <po:pol>M</po:pol>
        <po:datum_rodjenja>1976-10-26</po:datum_rodjenja>
    </po:osoba>
    <po:doze>
        <po:doza about="http://www.rokzasok.rs/rdf/database/doza/1"
                 vocab="http://www.rokzasok.rs/rdf/database/predicate">
            <po:tip>Pfizer-BioNtech</po:tip>
            <po:proizvodjac>BioNTech Manufacturing GMBH</po:proizvodjac>
            <po:datum>2020-08-19+02:00</po:datum>
            <po:broj_serije>broj_serije1</po:broj_serije>
            <po:broj_doze>1</po:broj_doze>
            <po:ustanova>
                <po:naziv>Dom Zdravlja</po:naziv>
                <po:mesto>Uzice</po:mesto>
            </po:ustanova>
        </po:doza>
        <po:doza about="http://www.rokzasok.rs/rdf/database/doza/2"
                 vocab="http://www.rokzasok.rs/rdf/database/predicate">
            <po:tip>Pfizer-BioNtech</po:tip>
            <po:proizvodjac>BioNTech Manufacturing GMBH</po:proizvodjac>
            <po:datum>2006-05-04</po:datum>
            <po:broj_serije>broj_serije1</po:broj_serije>
            <po:broj_doze>2</po:broj_doze>
            <po:ustanova>
                <po:naziv>Sajam</po:naziv>
                <po:mesto>Novi Sad</po:mesto>
            </po:ustanova>
        </po:doza>
    </po:doze>
    <po:razlog_izdavanja datatype="xs:string" property="pred:razlogIzdavanja">razlog_izdavanja0</po:razlog_izdavanja>
    <po:datum_izdavanja datatype="xs:date" property="pred:datumIzdavanja">2006-05-04</po:datum_izdavanja>
    <po:dokument_id>1</po:dokument_id>
</po:potvrda-vakcinacije>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/najnovija-potvrda-primer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<po:potvrda-vakcinacije xmlns:tp="http://www.rokzasok.rs/tipovi"
 xmlns:r="http://www.w3.org/ns/rdfa#"
 xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
 xmlns:po="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije potvrda_vakcinacije.xsd">
    <po:osoba>
        <po:jmbg>1234567891011</po:jmbg>
        <po:ime>Marko</po:ime>
        <po:prezime>Marković</po:prezime>
        <po:pol>M</po:pol>
        <po:datum_rodjenja>1952-10-07</po:datum_rodjenja>
        <po:id>1</po:id>
    </po:osoba>
    <po:doze>
        <po:doza>
            <po:tip>Sputnik V (Gamaleya istraživački centar)</po:tip>
            <po:proizvodjac>Gamaleya Institute</po:proizvodjac>
            <po:datum>2022-02-26</po:datum>
            <po:broj_serije>GAMALEYA01</po:broj_serije>
            <po:broj_doze>1</po:broj_doze>
            <po:ustanova>
                <po:naziv>Dom zdravlja</po:naziv>
                <po:mesto>Novi Sad</po:mesto>
            </po:ustanova>
        </po:doza>
        <po:doza>
            <po:tip>Sputnik V (Gamaleya istraživački centar)</po:tip>
            <po:proizvodjac>Gamaleya Institute</po:proizvodjac>
            <po:datum>2022-02-27</po:datum>
            <po:broj_serije>GAMALEYA02</po:broj_serije>
            <po:broj_doze>2</po:broj_doze>
            <po:ustanova>
                <po:naziv>Dom zdravlja</po:naziv>
                <po:mesto>Novi Sad</po:mesto>
            </po:ustanova>
        </po:doza>
    </po:doze>
    <po:qr_link>potvrda.com</po:qr_link>
    <po:datum_izdavanja>2022-02-27</po:datum_izdavanja>
    <po:dokument_id>1</po:dokument_id>
</po:potvrda-vakcinacije>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/bkp-primeri/potvrda_vakcinacije_primer-bkp.xml
<potvrda-vakcinacije xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
                         xmlns="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije"
                         xs:schemaLocation="http://www.rokzasok.rs/zdravstveni-radnik/potvrda-vakcinacije schema/potvrda_vakcinacije.xsd">
  <osoba>
    <jmbg>1234567890123</jmbg>
    <ime>Zdravko</ime>
    <prezime>Krivokapic</prezime>
    <pol>Z</pol>
    <datum_rodjenja>1976-10-26</datum_rodjenja>
  </osoba>
  <doze>
    <doza>
      <tip>Pfeizer-BioNTech</tip>
      <proizvodjac>BioNTech Manufacturing GMBH</proizvodjac>
      <datum>2020-08-19+02:00</datum>
      <broj_serije>string</broj_serije>
      <broj_doze>1</broj_doze>
      <ustanova>
        <naziv>Dom zdravlja</naziv>
        <mesto>Uzice</mesto>
      </ustanova>
    </doza>
    <doza>
      <tip>Sputnik V</tip>
      <proizvodjac>BioNTech Manufacturing GMBH</proizvodjac>
      <datum>2020-09-15</datum>
      <broj_serije>string</broj_serije>
      <broj_doze>2</broj_doze>
      <ustanova>
        <naziv>Sajam</naziv>
        <mesto>Novi Sad</mesto>
      </ustanova>
    </doza>
  </doze>
  <razlog_izdavanja>Putovanje u Njemacku</razlog_izdavanja>
  <datum_izdavanja>2013-12-21+01:00</datum_izdavanja>
  <dokument_id>12345678</dokument_id>
</potvrda-vakcinacije>
