=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/termini.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.rokzasok.rs/termini" xmlns:ter="www.rokzasok.rs/termini">
    <xs:element name="spisakTermina">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="ter:termini"> </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueMestoKey">
            <xs:selector xpath="ter:termini"/>
            <xs:field xpath="@mesto"/>
        </xs:unique>
    </xs:element>
    <xs:element name="dan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="maxBrojTermina" type="xs:positiveInteger"/>
                <xs:element name="brojZakazanihTermina" type="xs:nonNegativeInteger"/>
            </xs:sequence>
            <xs:attribute name="datum" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="termini">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="ter:dan"> </xs:element>
            </xs:sequence>
            <xs:attribute name="mesto" type="xs:string" use="required"/>
        </xs:complexType>
        <xs:unique name="uniqueDatumKey">
            <xs:selector xpath="./ter:dan"/>
            <xs:field xpath="@datum"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/termini_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<spisakTermina xmlns="www.rokzasok.rs/termini"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.rokzasok.rs/termini ./schema/termini.xsd">
    <termini mesto="mesto1">
        <dan datum="2006-05-04">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-05">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-06">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
    </termini>
    <termini mesto="mesto3">
        <dan datum="2006-05-04">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-05">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-06">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
    </termini>
    <termini mesto="mesto5">
        <dan datum="2006-05-04">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-05">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
        <dan datum="2006-05-06">
            <maxBrojTermina>50</maxBrojTermina>
            <brojZakazanihTermina>50</brojZakazanihTermina>
        </dan>
    </termini>
</spisakTermina>
