=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/schema/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat"
    xmlns:zh="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat"
    xmlns:tp="http://www.rokzasok.rs/tipovi" xmlns:r="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/">
    <xs:import namespace="http://www.rokzasok.rs/tipovi" schemaLocation="tipovi.xsd"/>
    <xs:element name="zahtev">
        <xs:complexType>
            <xs:all>
                <xs:element name="razlog_podnosenja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute default="pred:razlogPodnosenja" name="property"
                                    type="xs:string"/>
                                <xs:attribute default="xs:string" name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mesto">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute default="pred:mestoPodnosenja" name="property"
                                    type="xs:string"/>
                                <xs:attribute default="xs:string" name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute default="pred:datumPodnosenja" name="property"
                                    type="xs:string"/>
                                <xs:attribute default="xs:date" name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pacijent" type="zh:T_osoba"> </xs:element>
                <xs:element name="dokument_id" type="xs:positiveInteger"/>
                <xs:element name="status" minOccurs="0">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:boolean">
                                <xs:attribute default="pred:status" name="property" type="xs:string"/>
                                <xs:attribute default="xs:boolean" name="datatype" type="xs:string"
                                />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute fixed="http://www.rokzasok.rs/rdf/database/predicate" name="vocab"
                type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="T_osoba">
        <xs:sequence>
            <xs:element name="jmbg" type="tp:T_JMBG"/>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="pol" type="tp:T_pol"/>
            <xs:element name="datum_rodjenja" type="xs:date"/>
            <xs:element name="broj_pasosa" type="tp:T_broj_pasosa"/>
            <xs:element name="id">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:long">
                            <xs:attribute default="pred:kreiranOdStrane" name="property"
                                type="xs:string"/>
                            <xs:attribute default="xs:long" name="datatype" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/bkp-primeri/zahtev_za_sertifikat_primer-bkp.xml
<?xml version="1.0" encoding="UTF-8"?>
<zah:zahtev xmlns:zah="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat  schema/zahtev_za_sertifikat.xsd">
    <zah:razlog_podnosenja>Odlazak u kafic</zah:razlog_podnosenja>
    <zah:mesto>Novi Sad</zah:mesto>
    <zah:datum>2021-10-10</zah:datum>
    <zah:pacijent>
        <zah:jmbg>1702998158969</zah:jmbg>
        <zah:ime>Nikola</zah:ime>
        <zah:prezime>Anic</zah:prezime>
        <zah:pol>M</zah:pol>
        <zah:datum_rodjenja>1998-12-12</zah:datum_rodjenja>
        <zah:broj_pasosa>1234567890</zah:broj_pasosa>
    </zah:pacijent>
    <zah:dokument_id>1234567890</zah:dokument_id>
</zah:zahtev>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/zahtev_za_sertifikat_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<zh:zahtev xmlns:zh="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat"
           xmlns:tp="http://www.rokzasok.rs/tipovi"
           xmlns="http://www.w3.org/ns/rdfa#"
           xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat schema/zahtev_za_sertifikat.xsd"
           vocab="http://www.rokzasok.rs/rdf/database/predicate"
           about="http://www.rokzasok.rs/rdf/database/zahtev-za-sertifikat/1" rel="pred:kreiranOdStrane"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           href="http://www.rokzasok.rs/rdf/database/osoba/1702998158969"
>
    <zh:razlog_podnosenja datatype="xs:string" property="pred:razlogPodnosenja">Odlazak u kafic</zh:razlog_podnosenja>
    <zh:mesto property="pred:mestoPodnosenja" datatype="xs:string">Novi Sad</zh:mesto>
    <zh:datum datatype="xs:date" property="pred:datumPodnosenja">2021-10-10</zh:datum>
    <zh:pacijent idPacijenta="1" about="http://www.rokzasok.rs/rdf/database/osoba/1702998158969" vocab="http://www.rokzasok.rs/rdf/database/predicate">
        <zh:jmbg>1702998158969</zh:jmbg>
        <zh:ime>Nikola</zh:ime>
        <zh:prezime>Anic</zh:prezime>
        <zh:pol>M</zh:pol>
        <zh:datum_rodjenja>1998-12-12</zh:datum_rodjenja>
        <zh:broj_pasosa>1234567890</zh:broj_pasosa>
    </zh:pacijent>
    <zh:dokument_id>50</zh:dokument_id>
</zh:zahtev>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/zahtev_za_sertifikat_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<zh:zahtev xmlns:zh="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat"
           xmlns:tp="http://www.rokzasok.rs/tipovi"
           xmlns:r="http://www.w3.org/ns/rdfa#"
           xmlns:pred="http://www.rokzasok.rs/rdf/database/predicate/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="www.rokzasok.rs/gradjanin/zahtev-za-sertifikat schema/zahtev_za_sertifikat.xsd">
    <zh:razlog_podnosenja>Lični zahtev</zh:razlog_podnosenja>
    <zh:mesto>Novi Sad</zh:mesto>
    <zh:datum>2022-02-27</zh:datum>
    <zh:pacijent>
        <zh:jmbg>1234567891011</zh:jmbg>
        <zh:ime>Marko</zh:ime>
        <zh:prezime>Marković</zh:prezime>
        <zh:pol>M</zh:pol>
        <zh:datum_rodjenja>1952-10-07</zh:datum_rodjenja>
        <zh:broj_pasosa>1234567890</zh:broj_pasosa>
        <zh:id>1</zh:id>
    </zh:pacijent>
    <zh:dokument_id>1</zh:dokument_id>
</zh:zahtev>
