=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/schema/korisnici.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.rokzasok.rs/korisnici" xmlns:kor="www.rokzasok.rs/korisnici">

    <xs:element name="spisakKorisnika">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="kor:korisnik"> </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueKorisnickoIme">
            <xs:selector xpath="kor:korisnik"/>
            <xs:field xpath="@korisnickoIme"/>
        </xs:unique>
        <xs:unique name="uniqueId">
            <xs:selector xpath="kor:korisnik"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    <xs:element name="korisnik">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="lozinka" type="xs:string"/>
                <xs:element name="uloge">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="uloga">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="gradjanin"/>
                                        <xs:enumeration value="zdravstveni_radnik"/>
                                        <xs:enumeration value="sluzbenik"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="korisnickoIme" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:long" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== isidora-stanic/xml-projekat/sluzbenik/src/main/resources/data/korisnici_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<spisakKorisnika xmlns="www.rokzasok.rs/korisnici"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="www.rokzasok.rs/korisnici ./schema/korisnici.xsd">
    <korisnik korisnickoIme="korisnickoIme1" id="1" email="nekimail@info.com">
        <lozinka>lozinka0</lozinka>
        <uloge>
            <uloga>sluzbenik</uloga>
        </uloge>
    </korisnik>
    <korisnik korisnickoIme="korisnickoIme3" id="2" email="nekidrugimail@info.com">
        <lozinka>lozinka1</lozinka>
        <uloge>
            <uloga>sluzbenik</uloga>
        </uloge>
    </korisnik>
</spisakKorisnika>

=== isidora-stanic/xml-projekat/portal.za.imunizaciju/src/main/resources/data/korisnici_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<spisakKorisnika xmlns="www.rokzasok.rs/korisnici"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="www.rokzasok.rs/korisnici ./schema/korisnici.xsd">
    <korisnik korisnickoIme="korisnickoIme1" id="1">
        <lozinka>lozinka0</lozinka>
        <uloge>
            <uloga>gradjanin</uloga>
        </uloge>
    </korisnik>
    <korisnik korisnickoIme="korisnickoIme2" id="2">
        <lozinka>lozinka1</lozinka>
        <uloge>
            <uloga>zdravstveni_radnik</uloga>
        </uloge>
    </korisnik>
</spisakKorisnika>
